name: Test ZKS Spring

on:
  push:
    branches: [ master ]

jobs:
  setup-database:
    name: Setup Database
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: muvsdb
          POSTGRES_PASSWORD: muvsadmin
          POSTGRES_USER: muvsadmin
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install pg
      - name: Populate Database
        run: node client.js

  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build project with Maven
        run: mvn clean install
